/**
 * Projet CHOUETTE
 *
 * ce projet est sous license libre
 * voir LICENSE.txt pour plus de details
 *
 */
package fr.certu.chouette.model.neptune.type;

/**
 * @author michel
 *
 */
public enum PTNetworkSourceTypeEnum {
	AUTOMOBILECLUBPATROL, BREAKDOWNSERVICE, CAMERAOBSERVATION, EMERGENCYSERVICEPATROL, FREIGHTVEHICLEOPERATOR,
	INDIVIDUALSUBJECTOFTRAVELITINERARY, INDUCTIONLOOPMONITORINGSTATION, INFRAREDMONITORINGSTATION, MICROWAVEMONITORINGSTATION,
	MOBILETELEPHONECALLER, OTHERINFORMATION, OTHEROFFICIALVEHICLE, PASSENGERTRANSPORTCOORDINATINGAUTHORITY, POLICEPATROL,
	PUBLICANDPRIVATEUTILITIES, PUBLICTRANSPORT, REGISTEREDMOTORISTOBSERVER, ROADAUTHORITIES, ROADSIDETELEPHONECALLER,
	SPOTTERAIRCRAFT, TRAFFICMONITORINGSTATION, TRANSITOPERATOR, TRAVELAGENCY, TRAVELINFORMATIONSERVICEPROVIDER,
	VEHICLEPROBEMEASUREMENT, VIDEOPROCESSINGMONITORINGSTATION
}
