replicas: 3
image:
  identifier: ${artifact.metadata.image}

service:
  http:
    externalPort: 8080
    internalPort: 8080

resources:
  cpuLimit: "5"
  memLimit: 13000Mi
  cpuRequest: "4"
  memRequest: 12000Mi
  xmx: 11g
