image:
  identifier: ${artifact.metadata.image}

service:
  http:
    externalPort: 8080
    internalPort: 8080

resources:
  cpuLimit: "6"
  memLimit: 15000Mi
  cpuRequest: "5"
  memRequest: 14000Mi
  xmx: 12g
