replicas: 4
image:
  identifier: ${artifact.metadata.image}

service:
  http:
    externalPort: 8080
    internalPort: 8080

resources:
  cpuLimit: "4"
  memLimit: 10000Mi
  cpuRequest: "4"
  memRequest: 9000Mi
  xmx: 7g
