---
- set_fact: build_home="/usr/src/jenkinsbuild/workspace/chouette"
# - set_fact: build_home="/home/en/git/rutebanken/chouette"
- set_fact: build_log_directory="/usr/src/log"
- set_fact: logfile="{{build_log_directory}}/chouette.log"

- name: Make log directory structure
  file: path={{build_log_directory}} state=directory mode=0755 group=users

- name: Make chouette target directory structure
  file: path={{chouette_root}}/ state=directory mode=0755 group=users

- name: Upload the wildfly setup directory to the docker host
  synchronize: src=files/wildfly dest=/usr/src/chouette/.

- name: Upload disk usage notifier
  copy: src=disk_usage_notifier.sh dest=/usr/src/chouette/disk_usage_notifier.sh

- name: Upload jxm exporter config
  copy: src=jmx_exporter_config.yml dest=/usr/src/chouette/jmx_exporter_config.yml

- name: Copy the chouette sources to staging directory
  command: rsync -ar {{ build_home }}/chouette_iev/target/chouette.ear {{chouette_root}}/chouette.ear

- name: Move Dockerfile
  template: src=Dockerfile.j2 dest={{chouette_root}}/Dockerfile mode=0755

- name: Download postgresql jar file
  get_url: url=http://jump/postgresql-9.3-1103.jdbc41.jar
           dest={{ chouette_root }}/postgresql-9.3-1103.jdbc41.jar

- name: Download URLs
  shell: curl -s --netrc https://nexus.rutebanken.org/content/groups/public/{{ item.path }}/{{ item.filename }} -o {{ chouette_root }}/{{ item.filename }}
  with_items:
    - { path: "org/hibernate/hibernate-spatial/4.3", filename: "hibernate-spatial-4.3.jar" }
    - { path: "net/postgis/postgis-jdbc/2.1.7.2", filename: "postgis-jdbc-2.1.7.2.jar" }
    - { path: "com/vividsolutions/jts/1.13", filename: "jts-1.13.jar" }
    - { path: "com/sun/xml/bind/jaxb-impl/2.2.11", filename: "jaxb-impl-2.2.11.jar" }
    - { path: "com/sun/xml/bind/jaxb-core/2.2.11", filename: "jaxb-core-2.2.11.jar" }
    - { path: "com/sun/xml/bind/jaxb-xjc/2.2.11", filename: "jaxb-xjc-2.2.11.jar" }
    - { path: "xerces/xercesImpl/2.11.0.SP6-RB", filename: "xercesImpl-2.11.0.SP6-RB.jar" }

- name: Build the chouette docker image
  shell: docker build --tag={{ chouette_docker_image|quote }} --force-rm=true {{chouette_root}} > {{logfile}} 2>&1
  register: image

- name: Push chouette docker image if built
  when: image.changed
  shell: docker push {{ chouette_docker_image|quote }}
