# Adapted from https://github.com/prometheus/jmx_exporter/blob/master/example_configs/wildfly-10.yaml
---
lowercaseOutputName: true
lowercaseOutputLabelNames: true
whitelistObjectNames:
  # Whitelist objects to be collected, for performance reason
  # see https://github.com/prometheus/jmx_exporter/issues/246#issuecomment-367573931
  # Each object in the rules below has to be added to whitelistObjectNames too !
  # note that rules use regex (like "foo.*", whereas the whitelist use globbing expressions (like "foo*")
  - "jboss.as:subsystem=datasources,data-source=*,statistics=*"
  - "jboss.as:subsystem=datasources,xa-data-source=*,statistics=*"
  - "jboss.as:subsystem=transactions*"
  - "jboss.as:deployment=*,subdeployment=*,subsystem=*,servlet=*"
  # - "java.lang:*"
rules:
  - pattern: "^jboss.as<subsystem=datasources, (?:xa-)*data-source=(iev|chouette), statistics=(.+)><>(.+):"
    attrNameSnakeCase: true
    name: wildfly_datasource_$2_$3
    labels:
      name: $1

  - pattern: "^jboss.as<subsystem=transactions><>number_of_(.+):"
    attrNameSnakeCase: true
    name: wildfly_transaction_$1

  - pattern: "^jboss.as<deployment=(.+), subdeployment=(.+), subsystem=undertow, servlet=(.+)><>(.+time|.+count):"
    attrNameSnakeCase: true
    name: wildfly_servlet_$4
    type: GAUGE
    labels:
      name: $3
      deployment: $1
      subdeployment: $2
