#!/bin/bash -xe

# trace java version
#echo $JAVA_HOME
#java -version

if [ "$1" == "-classpath" ]; then
    OPTIONS="-Xbootclasspath/p:$2"
    cp `dirname $0`/log4j.properties $2/.
    cp $2/chouette.properties `dirname $0`/.
    shift 2
fi

cd `dirname $0`
java $OPTIONS -Duser.timezone=UTC -Xmx2000M -jar ${project.build.finalName}.jar $*
