drop table :SCH.company cascade;
drop table :SCH.connectionLink cascade;
drop table :SCH.routingConstraint_stoparea;
drop table :SCH.routingConstraint cascade;
drop table :SCH.stoparea cascade;
drop table :SCH.journeypattern cascade;
drop table :SCH.line cascade;
drop table :SCH.ptnetwork cascade;
drop table :SCH.route cascade;
drop table :SCH.stoppoint cascade;
drop table :SCH.timetable_date;
drop table :SCH.timetable_period;
drop table :SCH.timetable cascade;
drop table :SCH.timetablevehiclejourney cascade;
drop table :SCH.vehiclejourney cascade;
drop table :SCH.vehiclejourneyatstop cascade;
drop sequence :SCH.hibernate_sequence;
drop schema :SCH;