package fr.certu.chouette.service.validation;

public enum TransportMode {
	AIR, BICYCLE, BUS, COACH, FERRY, LOCALTRAIN, LONGDISTANCETRAIN, METRO, OTHER, PRIVATEVEHICLE, RAPIDTRANSIT,
	SHUTTLE, TAXI, TRAIN, TRAMWAY, TROLLEYBUS, VAL, WALK, WATERBORNE
}
