gcp_project = "entur-dev-1287"
gcp_resources_project = "entur-ror-dev"
gcp_cloudsql_project = "carbon-1287"
kube_namespace = "dev"
bucket_chouette_instance_name = "chouette-test"
location = "europe-west1"
service_account_bucket_role="roles/storage.admin"
