package fr.certu.chouette.service.validation;

public enum BoardingAlightingPossibility {
	ALIGHTONLY, ALIGHTONREQUEST, BOARDANDALIGHT, BOARDANDALIGHTONREQUEST, BOARDONLY, BOARDONREQUEST, NEITHERBOARDORALIGHT
}
