package fr.certu.chouette.service.validation;

public enum PTNetworkSourceType {
	AUTOMOBILECLUBPATROL, BREAKDOWNSERVICE, CAMERAOBSERVATION, EMERGENCYSERVICEPATROL, FREIGHTVEHICLEOPERATOR,
	INDIVIDUALSUBJECTOFTRAVELITINERARY, INDUCTIONLOOPMONITORINGSTATION, INFRAREDMONITORINGSTATION, MICROWAVEMONITORINGSTATION,
	MOBILETELEPHONECALLER, OTHERINFORMATION, OTHEROFFICIALVEHICLE, PASSENGERTRANSPORTCOORDINATINGAUTHORITY, POLICEPATROL,
	PUBLICANDPRIVATEUTILITIES, PUBLICTRANSPORT, REGISTEREDMOTORISTOBSERVER, ROADAUTHORITIES, ROADSIDETELEPHONECALLER,
	SPOTTERAIRCRAFT, TRAFFICMONITORINGSTATION, TRANSITOPERATOR, TRAVELAGENCY, TRAVELINFORMATIONSERVICEPROVIDER,
	VEHICLEPROBEMEASUREMENT, VIDEOPROCESSINGMONITORINGSTATION
}
