/**
 * Projet SYTADIN
 *
@ENTETE_LIVRAISON@
 *
 * $RCSFile$
 *
 * Date    : $Date$
 * Auteur  : $Author$
 * Version : $Revision$
 * 
 * Historique des modifications :
 * 
 * $Log$
 *
 *
 */
package fr.certu.chouette.service.commun;

/**
 * 
 */
public enum CodeDetailIncident
{
  DEFAULT,
  DATA,
  DATETIME_TYPE,
  DATE_TYPE,
  MALFORMED_ID,
  CONNECTIONLINK_DEPARTURE,
  CONNECTIONLINK_ARRIVAL,
  VEHICLEJOURNEYATSTOP_VEHICLEJOURNEY,
  VEHICLEJOURNEYATSTOP,
  ROUTE_STOPPOINTPOSITION,
  ROUTE_SWAPVEHICLEJOURNEYATSTOP,
  ROUTE_STOPPOINTFREEPOSITION,
  ROUTE_STOPPOINTDUPLICATEPOSITION,
  ROUTE_STOPPOINTDUPLICATETARGETSTOPPOINT,
  ROUTE_STOPPOINTCOLLUSIONSTOPPOINT,
  BOARDINGPOSITION_NAME,
  LINE_COUNT,
  COLUMN_COUNT,
  INIT_FAILED,
  TIMETABLE_POSITION,
  NETWORK_POSITION,
  COMPANY_POSITION,
  LINE_POSITION,
  INVALID_SYNTAX,
  TIMETABLE_DUPLICATEDATA,
  COLUMN_POSITION,
  PERIOD_STARTDATE,
  PERIOD_ENDDATE,
  NULL_ALIAS,
  DUPLICATE_ALIAS,
  INVALID_DATA,
  TIMETABLE_MISSINGDATA,
  VEHICLEJOURNEY_ORIENTATION,
  DUPLICATE_LINE,
  MISSING_DATA,
  UNEXPECTED_DATA,
  TIMETABLE_VEHICLEJOURNEY,
  UNKNOWN_ALIAS,
  VEHICLEJOURNEY_MISSINGDATA,
  STOPPOINT_LINK,
  MULTIPLE_PARENT,
  STOPPOINT_MISSINGPASSINGTIME,
  STOPPOINT_MALFORMEDPASSINGTIME,
  LINE_MISSINGDATA,
  NETWORK_MISSINGDATA,
  NETWORK_DUPLICATELINE,
  COMPANY_DUPLICATELINE,
  COMPANY_MISSINGDATA,
  STOPAREA_PARENT,
  TIMETABLE_MISSINGVEHICLEJOURNEY,
  LIST,
  STOPPOINT_ID,
  TIMETABLE_COUNT,
  ROUTE_VEHICLEJOURNEYMISMATCH,
  ROUTE_VEHICLEJOURNEYSTOPPOINTMISMATCH,
  ROUTE_JOURNEYPATTERNSTOPPOINTMISMATCH,
  ROUTE_JOURNEYPATTERNMISMATCH,
  
}
